// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwMtC7NOLU99OYQIP3TQG_OwY-zsN0wdg',
    appId: '1:384819839490:web:d87d721e9ff7ff1e431d1b',
    messagingSenderId: '384819839490',
    projectId: 'snoozesage',
    authDomain: 'snoozesage.firebaseapp.com',
    storageBucket: 'snoozesage.appspot.com',
    measurementId: 'G-2T294SM16D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOmphuRVTSEMF1IVeSCiJ2s19ANRIoTwE',
    appId: '1:384819839490:android:3e2477bad0abd835431d1b',
    messagingSenderId: '384819839490',
    projectId: 'snoozesage',
    storageBucket: 'snoozesage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzRevG4Jj9Tj4BYV7gBM1zg4fAU7_l9Hw',
    appId: '1:384819839490:ios:6c67a2bb60aec674431d1b',
    messagingSenderId: '384819839490',
    projectId: 'snoozesage',
    storageBucket: 'snoozesage.appspot.com',
    iosBundleId: 'com.example.demoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzRevG4Jj9Tj4BYV7gBM1zg4fAU7_l9Hw',
    appId: '1:384819839490:ios:6c67a2bb60aec674431d1b',
    messagingSenderId: '384819839490',
    projectId: 'snoozesage',
    storageBucket: 'snoozesage.appspot.com',
    iosBundleId: 'com.example.demoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwMtC7NOLU99OYQIP3TQG_OwY-zsN0wdg',
    appId: '1:384819839490:web:3f6647df1d16a13c431d1b',
    messagingSenderId: '384819839490',
    projectId: 'snoozesage',
    authDomain: 'snoozesage.firebaseapp.com',
    storageBucket: 'snoozesage.appspot.com',
    measurementId: 'G-9QMP87S9RT',
  );
}
